mailserver:
  hosts:
    138.197.171.62:
      ansible_python_interpreter: /usr/bin/python3
      mailcow_domain_name: mail.laafisoft.bf
web:
  hosts:
    138.197.171.62:
      ansible_python_interpreter: /usr/bin/python3
      user: ubuntu
      ansible_user: ubuntu
      docker: false
      php_version: 8.0
      domain: oza.dev
      domain_name: oza
      self_signed: false
      mysql_root_password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        34313066333363386564353732343335383039633131316165616165653163336262383333376433
        3534363434343236376131356130663835646531383938330a613030316363373264626637343364
        63623930373964323237626436646237633866393438306262656235303937323362643365633462
        3564333461616437320a663732623565383737616438393361626233333139396239363033626432
        63643337613933633364323564383134626662356361363632333565363133663865
      mysql_password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        66303934336130653437666130633630346231646635623661643535363839303832353932633866
        3865303864326639636435643031646234386339333032620a663834393434623432303937623961
        32383237396338373164666563376538616564313962313538353838646233393761356138636466
        6662366365313135640a636566616133386531376262666166646630303065353732643465303638
        64636362373564343233613964303566373438376437616630663134636235343839
      mysql_db: "{{ domain_name }}"
      mysql_user: "{{ domain_name }}"
      ansistrano_deploy_to: "/srv/oza.dev"
      ansistrano_git_repo: "git@github.com:oza75/oza.dev.git"
      ansistrano_git_branch: "master"
      ansistrano_git_identity_key_path: "~/.ssh/id_rsa"
      ansistrano_keep_releases: 5
      ansistrano_shared_paths: [ "storage" ]
      ansistrano_shared_files: [ ".env" ]
      ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/before_symlink.yml"
      ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/after_symlink.yml"
      ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/tasks/end.yml"
      ansistrano_deploy_via: git
      mail_password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        31346139326266396537343532326665666666396232623530336266393232656530633239363263
        6232616230663564326430336533343961646135353366390a666531316463303835633861303638
        65343734373335656566323534353734613738343765396262623163653261656534303366323966
        3031313835643331300a653866636530313162343731383564376665653536303936336364386239
        34663235323861616330323465613431346164363534346231396531373665393865
      mail_username: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65343361373862303733363661626232623630343365303339376661303364346533646365316530
        6363313037366564383831653638346262656662616636390a363335383230663866666363383661
        35346639383135393832373963376239643661643465353863353634393938326131646532386639
        3839353432663433640a363033653265636334316436666563636664616362626236656539353235
        63616666346235363562323539616666613764643430646635633334323830306164
