php_version: 7.4
domain: "{{ domain_name }}"
mysql_db: "{{ domain_name }}"
mysql_user: "{{ domain_name }}"
npm_globals:
  - yarn
ansistrano_deploy_to: "/srv/{{domain}}"
mysql_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34613538643831656666636238336636623631663734623865346365313431336662383561623931
  3165343439376130386234623766633637613265633931340a633835373566366434383761353532
  33366232366433333932633163613863383362333463666131353232393034373830623835326431
  6339616335333261310a633864646163356539633139663664366438366239373063346635353637
  30376264343263633231656638393033626234666532353035306663373930643037
mysql_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66636463366365316237323163643062643861663161623136343665336638336366306562386463
  6434363830333663356136386261346530346635313461360a393466356133333530356334376266
  36386366636634383039386265383132353039646430363435653465303062326537643938613461
  6261326436633232320a633931333965303631336466353433376664313830663734376535343466
  38393238623936396562313334633136326161356634333532646431623731333036

