---
- name: PHP | ADD ondrej/php repository
  apt_repository:
    repo: "ppa:ondrej/php"
- name: PHP | Install
  apt:
    update_cache: yes
    state: present
    name:
      - "php{{ php_version }}-redis"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-ctype"
      - "php{{ php_version }}-iconv"
#      - "php{{ php_version }}-json"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-pgsql"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-imagick"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-gmp"
      - "php-redis"
- name: PHP | Composer
  script:
    cmd: ../files/composer.sh
    creates: /usr/local/bin/composer
- name: PHP | Disable Errors
  lineinfile:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "display_errors ="
    line: "display_errors = 0"
  notify: php restart
