---
- name: MySQL | Install
  apt:
    state: present
    name:
      - mysql-server
      - libmysqlclient-dev
      - python3-dev
      - python3-mysqldb
- name: "MySQL | Set root password"
  mysql_user:
    check_implicit_admin: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    host: localhost
    password: "{{ mysql_root_password }}"
- name: MySQL | Remove anon
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: ""
    state: absent
- name: MySQL | Remove test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent
- name: "MySQL | Create Database {{ mysql_db }}"
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ mysql_db }}"
    state: present
- name: "MySQL | Create User {{ mysql_user }}"
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: localhost
    priv: "{{ mysql_db }}.*:ALL"
    state: present
